# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Criterioncontext.create(name: 'location')
Criterioncontext.create(name: 'costrate')
Criterioncontext.create(name: 'seniority')
Criterioncontext.create(name: 'skill')
Criterioncontext.create(name: 'interest')
Criterioncontext.create(name: 'other')

Jobprofile.create(code: 'JP_soft', name: 'Software Engineer')
Jobprofile.create(code: 'JP_cto', name: 'CTO')
Jobprofile.create(code: 'JP_teach', name: 'Teaching Assistant')
Jobprofile.create(code: 'JP_projass', name: 'Project Assistant')
Jobprofile.create(code: 'JP_projlead', name: 'Project Leader')

#Testdata
Employee.create(firstname: 'Lukas', surname: 'von Rotz', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '140', jobprofile_id: 1)
Employee.create(firstname: 'Oscar', surname: 'Meier', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '40', jobprofile_id: 2)
Employee.create(firstname: 'Adrian', surname: 'Kölliker', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '120', jobprofile_id: 1)
Employee.create(firstname: 'Mirjam', surname: 'Läderach', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '100', jobprofile_id: 3)
Employee.create(firstname: 'Alexandra', surname: 'Barden', loclat: '47.56', loclon: '5.56', country: 'Germany', costrate: '110', jobprofile_id: 4)
Employee.create(firstname: 'Matthias', surname: 'Stürmer', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '200', jobprofile_id: 5)
Employee.create(firstname: 'Janik', surname: 'Endtner', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '130', jobprofile_id: 1)
Employee.create(firstname: 'Petar', surname: 'Kovac', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '130', jobprofile_id: 4)
Employee.create(firstname: 'Ursula', surname: 'Jakob', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '130', jobprofile_id: 4)
Employee.create(firstname: 'Julia', surname: 'Schächtele', loclat: '47.56', loclon: '5.56', country: 'Switzerland', costrate: '130', jobprofile_id: 4)

Criterion.create(criterioncontext_id: 1, name: 'location')
Criterion.create(criterioncontext_id: 2, name: 'costrate')
Criterion.create(criterioncontext_id: 3, name: 'seniority')
Criterion.create(criterioncontext_id: 4, name: 'skill1')
Criterion.create(criterioncontext_id: 4, name: 'skill2')
Criterion.create(criterioncontext_id: 4, name: 'skill3')
Criterion.create(criterioncontext_id: 5, name: 'interest1')
Criterion.create(criterioncontext_id: 5, name: 'interest2')
Criterion.create(criterioncontext_id: 5, name: 'interest3')
Criterion.create(criterioncontext_id: 6, name: 'price')
Criterion.create(criterioncontext_id: 6, name: 'vmax')
Criterion.create(criterioncontext_id: 6, name: 'c120')
Criterion.create(criterioncontext_id: 6, name: 'coff')
Criterion.create(criterioncontext_id: 6, name: 'acce')
Criterion.create(criterioncontext_id: 6, name: 'frei')
Criterion.create(criterioncontext_id: 6, name: 'brui')

Criterionvalue.create(employee_id: '1', criterion_id: '10', value: '103000')
Criterionvalue.create(employee_id: '1', criterion_id: '11', value: '171.3')
Criterionvalue.create(employee_id: '1', criterion_id: '12', value: '7.65')
Criterionvalue.create(employee_id: '1', criterion_id: '13', value: '352')
Criterionvalue.create(employee_id: '1', criterion_id: '14', value: '11.6')
Criterionvalue.create(employee_id: '1', criterion_id: '15', value: '88')
Criterionvalue.create(employee_id: '1', criterion_id: '16', value: '69.7')
Criterionvalue.create(employee_id: '2', criterion_id: '10', value: '101300')
Criterionvalue.create(employee_id: '2', criterion_id: '11', value: '205.3')
Criterionvalue.create(employee_id: '2', criterion_id: '12', value: '7.9')
Criterionvalue.create(employee_id: '2', criterion_id: '13', value: '203')
Criterionvalue.create(employee_id: '2', criterion_id: '14', value: '8.4')
Criterionvalue.create(employee_id: '2', criterion_id: '15', value: '78.3')
Criterionvalue.create(employee_id: '2', criterion_id: '16', value: '73.4')
Criterionvalue.create(employee_id: '3', criterion_id: '10', value: '156400')
Criterionvalue.create(employee_id: '3', criterion_id: '11', value: '221.7')
Criterionvalue.create(employee_id: '3', criterion_id: '12', value: '7.9')
Criterionvalue.create(employee_id: '3', criterion_id: '13', value: '391')
Criterionvalue.create(employee_id: '3', criterion_id: '14', value: '8.4')
Criterionvalue.create(employee_id: '3', criterion_id: '15', value: '81.5')
Criterionvalue.create(employee_id: '3', criterion_id: '16', value: '69')
Criterionvalue.create(employee_id: '4', criterion_id: '10', value: '267400')
Criterionvalue.create(employee_id: '4', criterion_id: '11', value: '230.7')
Criterionvalue.create(employee_id: '4', criterion_id: '12', value: '10.5')
Criterionvalue.create(employee_id: '4', criterion_id: '13', value: '419')
Criterionvalue.create(employee_id: '4', criterion_id: '14', value: '8.6')
Criterionvalue.create(employee_id: '4', criterion_id: '15', value: '64.7')
Criterionvalue.create(employee_id: '4', criterion_id: '16', value: '65.6')
Criterionvalue.create(employee_id: '5', criterion_id: '10', value: '49900')
Criterionvalue.create(employee_id: '5', criterion_id: '11', value: '122.6')
Criterionvalue.create(employee_id: '5', criterion_id: '12', value: '8.3')
Criterionvalue.create(employee_id: '5', criterion_id: '13', value: '120')
Criterionvalue.create(employee_id: '5', criterion_id: '14', value: '23.7')
Criterionvalue.create(employee_id: '5', criterion_id: '15', value: '74.1')
Criterionvalue.create(employee_id: '5', criterion_id: '16', value: '76.4')
Criterionvalue.create(employee_id: '6', criterion_id: '10', value: '103600')
Criterionvalue.create(employee_id: '6', criterion_id: '11', value: '205.1')
Criterionvalue.create(employee_id: '6', criterion_id: '12', value: '8.2')
Criterionvalue.create(employee_id: '6', criterion_id: '13', value: '265')
Criterionvalue.create(employee_id: '6', criterion_id: '14', value: '8.1')
Criterionvalue.create(employee_id: '6', criterion_id: '15', value: '81.7')
Criterionvalue.create(employee_id: '6', criterion_id: '16', value: '73.6')
Criterionvalue.create(employee_id: '7', criterion_id: '10', value: '103000')
Criterionvalue.create(employee_id: '7', criterion_id: '11', value: '178')
Criterionvalue.create(employee_id: '7', criterion_id: '12', value: '7.2')
Criterionvalue.create(employee_id: '7', criterion_id: '13', value: '419')
Criterionvalue.create(employee_id: '7', criterion_id: '14', value: '11.4')
Criterionvalue.create(employee_id: '7', criterion_id: '15', value: '77.6')
Criterionvalue.create(employee_id: '7', criterion_id: '16', value: '66.2')
Criterionvalue.create(employee_id: '8', criterion_id: '10', value: '170100')
Criterionvalue.create(employee_id: '8', criterion_id: '11', value: '226')
Criterionvalue.create(employee_id: '8', criterion_id: '12', value: '9.1')
Criterionvalue.create(employee_id: '8', criterion_id: '13', value: '419')
Criterionvalue.create(employee_id: '8', criterion_id: '14', value: '8.1')
Criterionvalue.create(employee_id: '8', criterion_id: '15', value: '74.7')
Criterionvalue.create(employee_id: '8', criterion_id: '16', value: '71.7')
Criterionvalue.create(employee_id: '9', criterion_id: '10', value: '279700')
Criterionvalue.create(employee_id: '9', criterion_id: '11', value: '233.8')
Criterionvalue.create(employee_id: '9', criterion_id: '12', value: '10.9')
Criterionvalue.create(employee_id: '9', criterion_id: '13', value: '359')
Criterionvalue.create(employee_id: '9', criterion_id: '14', value: '7.8')
Criterionvalue.create(employee_id: '9', criterion_id: '15', value: '75.5')
Criterionvalue.create(employee_id: '9', criterion_id: '16', value: '70.9')
Criterionvalue.create(employee_id: '10', criterion_id: '10', value: '405000')
Criterionvalue.create(employee_id: '10', criterion_id: '11', value: '265')
Criterionvalue.create(employee_id: '10', criterion_id: '12', value: '10.3')
Criterionvalue.create(employee_id: '10', criterion_id: '13', value: '265')
Criterionvalue.create(employee_id: '10', criterion_id: '14', value: '6')
Criterionvalue.create(employee_id: '10', criterion_id: '15', value: '74.7')
Criterionvalue.create(employee_id: '10', criterion_id: '16', value: '72')
Criterionvalue.create(employee_id: '6', criterion_id: '1', value: '4')
Criterionvalue.create(employee_id: '6', criterion_id: '2', value: '4')
Criterionvalue.create(employee_id: '6', criterion_id: '3', value: '11')
Criterionvalue.create(employee_id: '6', criterion_id: '4', value: '12')
Criterionvalue.create(employee_id: '6', criterion_id: '5', value: '13')
Criterionvalue.create(employee_id: '6', criterion_id: '6', value: '21')
Criterionvalue.create(employee_id: '6', criterion_id: '7', value: '22')
Criterionvalue.create(employee_id: '6', criterion_id: '8', value: '23')
Criterionvalue.create(employee_id: '6', criterion_id: '9', value: '24')
Criterionvalue.create(employee_id: '7', criterion_id: '1', value: '4')
Criterionvalue.create(employee_id: '7', criterion_id: '2', value: '4')
Criterionvalue.create(employee_id: '7', criterion_id: '3', value: '1')
Criterionvalue.create(employee_id: '7', criterion_id: '4', value: '1')
Criterionvalue.create(employee_id: '7', criterion_id: '5', value: '1')
Criterionvalue.create(employee_id: '7', criterion_id: '6', value: '2')
Criterionvalue.create(employee_id: '7', criterion_id: '7', value: '2')
Criterionvalue.create(employee_id: '7', criterion_id: '8', value: '2')
Criterionvalue.create(employee_id: '7', criterion_id: '9', value: '2')

Project.create(name: 'Projekt1', loclat: '45.55', loclon: '6.54', startdate: '01.01.2017', enddate: '20.02.2017', effort: '30', hourlyrate: '200', user_id: '1')
Project.create(name: 'Projekt2', loclat: '45.55', loclon: '6.54', startdate: '01.01.2017', enddate: '20.02.2017', effort: '30', hourlyrate: '200', user_id: '1')

Criterionparam.create(project_id: '1', criterion_id: '10', weight: '0.3', direction: 'false', prefthresslo: '0.115', prefthresint: '-2654.87', inthresslo: '0.08', inthresint: '-2000', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '500000')
Criterionparam.create(project_id: '1', criterion_id: '11', weight: '0.1', direction: 'true', prefthresslo: '0.05', prefthresint: '0', inthresslo: '0.02', inthresint: '0', filterlow: '0', filterhigh: '300')
Criterionparam.create(project_id: '1', criterion_id: '12', weight: '0.3', direction: 'false', prefthresslo: '0', prefthresint: '2', inthresslo: '0', inthresint: '1', vetothresslo: '0', vetothresint: '4', filterlow: '0', filterhigh: '15')
Criterionparam.create(project_id: '1', criterion_id: '13', weight: '0.2', direction: 'true', prefthresslo: '0', prefthresint: '200', inthresslo: '0', inthresint: '100', filterlow: '0', filterhigh: '500')
Criterionparam.create(project_id: '1', criterion_id: '14', weight: '0.1', direction: 'false', prefthresslo: '0.2', prefthresint: '-1', inthresslo: '0.1', inthresint: '-0.5', vetothresslo: '0.5', vetothresint: '3', filterlow: '0', filterhigh: '25')
Criterionparam.create(project_id: '1', criterion_id: '15', weight: '0.2', direction: 'false', prefthresslo: '0', prefthresint: '5', inthresslo: '0', inthresint: '0', vetothresslo: '0', vetothresint: '15', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '1', criterion_id: '16', weight: '0.1', direction: 'false', prefthresslo: '0', prefthresint: '5', inthresslo: '0', inthresint: '3', vetothresslo: '0', vetothresint: '15', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '1', weight: '0.1', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '2', weight: '0.1', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '3', weight: '0.05', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '4', weight: '0.05', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '5', weight: '0.1', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '6', weight: '0.25', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '7', weight: '0.25', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '100')
Criterionparam.create(project_id: '2', criterion_id: '8', weight: '0.25', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '200')
Criterionparam.create(project_id: '2', criterion_id: '9', weight: '0.25', direction: 'false', prefthresslo: '0.08', prefthresint: '-2000', inthresslo: '0.115', inthresint: '-2654.87', vetothresslo: '0.474', vetothresint: '26315.79', filterlow: '0', filterhigh: '200')

Week.create(workweek: '49', year:'2016')
Week.create(workweek: '50', year:'2016')
Week.create(workweek: '51', year:'2016')
Week.create(workweek: '52', year:'2016')
Week.create(workweek: '1', year:'2017')
Week.create(workweek: '2', year:'2017')
Week.create(workweek: '3', year:'2017')
Week.create(workweek: '4', year:'2017')
Week.create(workweek: '5', year:'2017')
Week.create(workweek: '6', year:'2017')
Week.create(workweek: '7', year:'2017')
Week.create(workweek: '8', year:'2017')
Week.create(workweek: '9', year:'2017')
Week.create(workweek: '10', year:'2017')

Workload.create(employee_id: '1', week_id: '1', free: '5', offered: '10', sold: '15', absent: '20')
Workload.create(employee_id: '1', week_id: '2', free: '10', offered: '15', sold: '20', absent: '25')
Workload.create(employee_id: '2', week_id: '1', free: '15', offered: '20', sold: '25', absent: '30')
Workload.create(employee_id: '2', week_id: '2', free: '0', offered: '5', sold: '10', absent: '15')
